# Generated by Django 5.0.7 on 2024-08-13 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_product_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
