# Generated by Django 5.0.7 on 2024-08-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("price", models.FloatField()),
                ("digital", models.BooleanField(default=False, null=True)),
                ("detail", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="product", to="members.category"
                    ),
                ),
            ],
        ),
    ]
