# Generated by Django 5.0.7 on 2024-08-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.shippingaddress",
            ),
        ),
    ]
