# Generated by Django 5.0.7 on 2024-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="members/static/images/"
            ),
        ),
    ]
